# Generated by Django 3.2.7 on 2021-11-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('source', models.URLField(blank=True)),
                ('descriptions', models.CharField(blank=True, max_length=1500)),
            ],
        ),
    ]
