# Generated by Django 3.2.7 on 2021-11-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211103_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
